CREATE PROCEDURE [dbo].[SP_TongTienHocPhi] @MALOP varchar(10), @NienKhoa varchar(9), @HocKy int
AS

DECLARE @tonghocphi INT
;with GETSVDONGTIEN(MASV,HOCPHI,SOTIENDONG)
as
(select HOCPHI.MASV,HOCPHI,SOTIENDADONG = SUM(SOTIENDONG) 
from HOCPHI left join CT_DONGHOCPHI
on HOCPHI.MASV = CT_DONGHOCPHI.MASV AND CT_DONGHOCPHI.HOCKY = HOCPHI.HOCKY AND CT_DONGHOCPHI.NIENKHOA = HOCPHI.NIENKHOA
where HOCPHI.NIENKHOA = @NienKhoa AND HOCPHI.HOCKY = @HocKy
group by HOCPHI.MASV,HOCPHI)
select @tonghocphi =SUM(A.SOTIENDONG) from (select HOTEN=SINHVIEN.HO + ' '+ SINHVIEN.TEN,HOCPHI,SOTIENDONG= COALESCE(SOTIENDONG,0)  
from SINHVIEN,GETSVDONGTIEN
where SINHVIEN.MASV = GETSVDONGTIEN.MASV
AND SINHVIEN.MALOP = @MALOP) as A
PRINT(@tonghocphi)
IF(@tonghocphi IS NULL) 
SELECT TONGHOCPHI = 0
ELSE SELECT TONGHOCPHI = @tonghocphi

create PROCEDURE [dbo].[SP_InDanhSachDongHP] @MALOP varchar(10), @NienKhoa varchar(9), @HocKy int
as
with GETSVDONGTIEN(MASV,HOCPHI,SOTIENDONG)
as
(select HOCPHI.MASV,HOCPHI,SOTIENDADONG = SUM(SOTIENDONG) 
from HOCPHI left join CT_DONGHOCPHI
on HOCPHI.MASV = CT_DONGHOCPHI.MASV AND CT_DONGHOCPHI.HOCKY = HOCPHI.HOCKY AND CT_DONGHOCPHI.NIENKHOA = HOCPHI.NIENKHOA
where HOCPHI.NIENKHOA = @NienKhoa AND HOCPHI.HOCKY = @HocKy
group by HOCPHI.MASV,HOCPHI)
select HOTEN=SINHVIEN.HO + ' '+ SINHVIEN.TEN,HOCPHI,SOTIENDONG= COALESCE(SOTIENDONG,0)  
from SINHVIEN,GETSVDONGTIEN
where SINHVIEN.MASV = GETSVDONGTIEN.MASV
AND SINHVIEN.MALOP = @MALOP